export const STUDENT_REPOSITORY = Symbol('STUDENT_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CONTRACT_REPOSITORY = Symbol('CONTRACT_REPOSITORY');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
